apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: shopping-cart-service
          image: stwomack/shopping-cart-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-secrets